(function(g){var window=this;'use strict';var Vn=function(k){k.publish("cardstatechange",k.tO()&&k.Sw()?1:0)},MY=function(k,F){var a=g.P1(F);
const V=a?F:arguments;for(a=a?0:1;a<V.length;a++){if(k==null)return;k=k[V[a]]}return k},mLB=function(k){const F=g.iv(k);
k=g.kd(k);return new g.vg(F.x,F.y,k.width,k.height)},Smz=function(k,F,a){let V;
return V=g.jY(k,F,function(){g.Wd(V);a.apply(k,arguments)},{})},Xo=function(k){k=g.QX(k);
delete CJ[k];g.NL(CJ)&&si&&si.stop()},ezm=function(){si||(si=new g.La(function(){ZzL()},20));
const k=si;k.isActive()||k.start()},ZzL=function(){var k=g.xp();
g.BZ(CJ,function(F){dLS(F,k)});
g.NL(CJ)||ezm()},Ui=function(k,F,a,V){g.bP.call(this);
if(!Array.isArray(k)||!Array.isArray(F))throw Error("Start and end parameters must be arrays");if(k.length!=F.length)throw Error("Start and end points must be the same length");this.K=k;this.T=F;this.duration=a;this.Z=V;this.coords=[];this.progress=this.C=0;this.V=null},dLS=function(k,F){F<k.startTime&&(k.endTime=F+k.endTime-k.startTime,k.startTime=F);
k.progress=(F-k.startTime)/(k.endTime-k.startTime);k.progress>1&&(k.progress=1);k.C=1E3/(F-k.V);k.V=F;PR8(k,k.progress);k.progress==1?(k.D=0,Xo(k),k.onFinish(),k.ji()):k.isPlaying()&&k.wd()},PR8=function(k,F){typeof k.Z==="function"&&(F=k.Z(F));
k.coords=Array(k.K.length);for(let a=0;a<k.K.length;a++)k.coords[a]=(k.T[a]-k.K[a])*F+k.K[a]},HzS=function(k,F){g.wF.call(this,k);
this.coords=F.coords;this.x=F.coords[0];this.y=F.coords[1];this.z=F.coords[2];this.duration=F.duration;this.progress=F.progress;this.fps=F.C;this.state=F.D},yn=function(k,F,a,V,M){Ui.call(this,F,a,V,M);
this.element=k},oP=function(k,F,a,V,M){if(F.length!=2||a.length!=2)throw Error("Start and end points must be 2D");
yn.call(this,k,F,a,V,M)},JSk=function(k){return Math.pow(k,3)},Qmz=function(k){return 3*k*k-2*k*k*k},nJ=function(k){return k.baseUrl||null},uD=function(k,F){return g.Gm(g.bb(k,F),a=>!!a)},rSX=function(k,F,a){function V(Sf){var RH=Sf.hovercardButton;
if(!RH)return null;RH=RH.subscribeButtonRenderer;if(!RH)return null;const zm=C(RH.unsubscribedButtonText),hB=C(RH.subscribedButtonText);let jf,Xy;RH.subscribed?(jf=C(RH.subscriberCountWithUnsubscribeText),Xy=C(RH.subscriberCountText)):(jf=C(RH.subscriberCountText),Xy=C(RH.subscriberCountWithSubscribeText));let Wx=null;return Sf.signinEndpoint&&((Wx=MY(Sf,"signinEndpoint","webNavigationEndpointData","url"))||(Wx=g.p(RH.signInEndpoint?.commandMetadata,g.Xt)?.url),!Wx)?null:zm&&(hB||Wx)?{subscribed:RH.subscribed,
subscribeText:zm,subscribeCount:jf,unsubscribeText:hB,unsubscribeCount:Xy,enabled:RH.enabled,signinUrl:Wx,classic:Sf.useClassicSubscribeButton}:null}
function M(Sf){if(Sf){var RH=[],zm=Sf.videoId;zm&&RH.push("v="+zm);(zm=Sf.playlistId)&&RH.push("list="+zm);(Sf=Sf.startTimeSeconds)&&RH.push("t="+Sf);return"/watch?"+RH.join("&")}}
function C(Sf){if(!Sf)return null;const RH=Sf.simpleText;return RH?RH:Sf.runs?g.bb(Sf.runs,zm=>zm.text).join(""):null}
F=F.endscreenElementRenderer;if(!F)return null;const X=F.style,U=F.endpoint||{};let y=null;var n=null,u=!1;let K=null,q=null,T=null,S=null;var J=!1;let x=null,O=null;var A=null;let l=null,t=null,M7=null;if(X==="VIDEO")g.p(U,g.JP)?y=g.p(U,g.JP).url:(M7=g.p(U,g.Mm),y=M(M7)),n=!1,K=k,F.thumbnailOverlays?(u=F.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,q=C(u.text),u=u.style==="LIVE"):q=C(F.videoDuration);else if(X==="PLAYLIST")g.p(U,g.JP)?y=g.p(U,g.JP).url:(M7=g.p(U,g.Mm),y=M(M7)),n=!1,K=
k,T=C(F.playlistLength);else if(X==="CHANNEL"){if(J=MY(U,"browseEndpoint","browseId"))S=J,y=`/channel/${S}`;n=!1;K="new";(J=!!F.isSubscribe)?x=V(F):O=C(F.subscribersText)}else X==="WEBSITE"?((A=MY(U,"urlEndpoint","url"))&&(y=A),n=!0,K="new",A=F.icon.thumbnails[0].url):X==="CREATOR_MERCHANDISE"&&(F.productPrice&&(l=C(F.productPrice)),F.additionalFeesText&&(t=C(F.additionalFeesText)),(n=MY(U,"urlEndpoint","url"))&&(y=n),n=!0,K="new");k=MY(F,"title","accessibility","accessibilityData","label");const X9=
F.endpoint?F.endpoint.clickTrackingParams:null;let LQ="";if(F.metadata){const Sf=C(F.metadata);Sf&&(LQ=Sf)}return{id:`element-${a}`,type:X,title:C(F.title),metadata:LQ,callToAction:C(F.callToAction),zs:F.image,iconUrl:A,left:Number(F.left),width:Number(F.width),top:Number(F.top),aspectRatio:Number(F.aspectRatio),startMs:Math.floor(Number(F.startMs)),endMs:Math.floor(Number(F.endMs)),videoDuration:q,VH:u,playlistLength:T,channelId:S,subscribeButton:x,subscribersText:O,isSubscribe:J,targetUrl:y||null,
kG:n,sessionData:X9?{itct:X9}:null,Ej:K,us:k?k:null,isPlaceholder:F.isPlaceholder,impressionUrls:uD(F.impressionUrls||[],nJ),le:uD(F.hovercardShowUrls||[],nJ),clickUrls:uD(U.loggingUrls||[],nJ),visualElement:g.nl(F.trackingParams),productPrice:l,additionalFeesText:t,watchEndpoint:M7||null}},KJ=function(k,F){const a={startMs:Math.floor(Number(k.startMs)),
impressionUrls:uD(k.impressionUrls||[],nJ),elements:uD(k.elements||[],(V,M)=>rSX(F,V,M))};
k.trackingParams&&(a.visualElement=g.nl(k.trackingParams));return a},qY=function(k){return k.player.S().playerStyle==="creator-endscreen-editor"},hz7=function(k){return k.player.getVideoData().Ix?"current":k.X?"new":"current"},gh=function(k,F,a=!0){k.player.Cv("creatorendscreen");
k.O&&(k.O.dispose(),k.O=null,k.Z.dispose(),k.Z=null);for(var V of Object.values(k.K))V.dispose();k.K={};k.C={};k.W.length>0&&(k.W.forEach(M=>{M.dispose()}),k.W.length=0);
k.D&&(g.fa(k.D,"ytp-ce-element-show"),k.D.setAttribute("aria-hidden","true"));k.T=0;if((k.endscreen=F)&&F.elements){a&&xLz(k);a=[];V=new g.rZ(F.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});a.push(V);k.player.S().K||(k.O=new g.G({U:"div",G:"ytp-ce-shadow"}),g.Ii(k.player,k.O.element,4),k.Z=new g.rz(k.O,200));for(V=0;V<F.elements.length;++V){const M=F.elements[V],C=ASR(k,M);if(!C){g.HS(new g.o5("buildEndscreenElement null",M));continue}k.K[M.id]=C;k.C[M.id]=M;g.Ii(k.player,
C.element,4);const X=new g.rZ(M.startMs,M.endMs,{id:"ytp-ce-element-"+M.id,namespace:"creatorendscreen"});a.push(X);Bkm(k,C,M)}k.player.KL(a);k.jd()}},Ymm=function(k){var F=k.player.getVideoData(),a=F.videoId;
k.V&&k.V.abort();a={method:"POST",onFinish:M=>{var C=k.V=null;M.status===200&&(M=M.responseText,M.substring(0,3)===")]}"&&(M=M.substring(3),C=JSON.parse(M),C=KJ(C,hz7(k))));gh(k,C)},
urlParams:{v:a},withCredentials:!0};k.X&&(a.urlParams.ptype="embedded");const V=F.k6;V&&(a.postParams={ad_tracking:V});if(F=g.Hdb(F))if(F=g.$g(F),F=g.LA(F))k.V=g.vM(F,a)},xLz=function(k){const F=g.qi(),a=g.g4();
a&&F&&k.endscreen.visualElement&&g.FN(g.tI)(void 0,a,F,k.endscreen.visualElement)},ASR=function(k,F){var a=null;
switch(F.type){case "VIDEO":k={U:"div",mN:["ytp-ce-element","ytp-ce-video"],L:{tabindex:"0","aria-label":F.us||"","aria-hidden":"true"},Y:[{U:"div",G:"ytp-ce-element-shadow"},{U:"div",G:"ytp-ce-covering-image",L:T7(F)},{U:"div",G:"ytp-ce-covering-shadow-top"},{U:"a",G:"ytp-ce-covering-overlay",L:{href:IP(k,F.targetUrl),tabindex:"-1"},Y:[{U:"div",mN:["ytp-ce-video-title","ytp-webkit-ellipsis"],L:{dir:g.sd(F.title||"")},EO:F.title},{U:"div",G:F.VH?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
EO:F.videoDuration||void 0}]}]};a=new g.G(k);break;case "PLAYLIST":k={U:"div",mN:["ytp-ce-element","ytp-ce-playlist"],L:{tabindex:"0","aria-label":F.us||"","aria-hidden":"true"},Y:[{U:"div",G:"ytp-ce-element-shadow"},{U:"div",G:"ytp-ce-covering-image",L:T7(F)},{U:"div",G:"ytp-ce-covering-shadow-top"},{U:"a",G:"ytp-ce-covering-overlay",L:{href:IP(k,F.targetUrl),tabindex:"-1"},Y:[{U:"div",mN:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],L:{dir:g.sd(F.title||"")},EO:F.title},{U:"div",G:"ytp-ce-playlist-count",
Y:[{U:"div",G:"ytp-ce-playlist-icon"},{U:"div",G:"ytp-ce-playlist-count-text",EO:F.playlistLength||void 0}]}]}]};a=new g.G(k);break;case "CHANNEL":a={U:"div",mN:["ytp-ce-element","ytp-ce-channel",F.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],L:{tabindex:"0","aria-label":F.us||"","aria-hidden":"true"},Y:[{U:"div",G:"ytp-ce-element-shadow"},{U:"div",G:"ytp-ce-expanding-overlay",Y:[{U:"div",G:"ytp-ce-expanding-overlay-hider"},{U:"div",G:"ytp-ce-expanding-overlay-background"},{U:"div",G:"ytp-ce-expanding-overlay-content",
Y:[{U:"div",G:"ytp-ce-expanding-overlay-body",Y:[{U:"div",G:"ytp-ce-expanding-overlay-body-padding",Y:[{U:"a",mN:["ytp-ce-channel-title","ytp-ce-link"],L:{href:IP(k,F.targetUrl),target:"_blank",tabindex:"-1",dir:g.sd(F.title||"")},EO:F.title},F.subscribeButton?{U:"div",G:"ytp-ce-subscribe-container",Y:[{U:"div",G:"ytp-ce-channel-subscribe"}]}:"",F.subscribersText?{U:"div",G:"ytp-ce-channel-subscribers-text",EO:F.subscribersText}:"",F.metadata?{U:"div",mN:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],EO:F.metadata}:""]}]}]}]},{U:"div",G:"ytp-ce-expanding-image",L:T7(F)}]};a=new g.G(a);const M=g.wS(document,"div","ytp-ce-channel-subscribe",a.element)[0];if(F.subscribeButton&&F.channelId){g.Dz(M,"ytp-ce-subscribe-button");let C;if(k.player.S().K){var V=null;C=F.sessionData.itct}else V="endscreen",C=null;V=new g.ac(F.subscribeButton.subscribeText,F.subscribeButton.subscribeCount,F.subscribeButton.unsubscribeText,F.subscribeButton.unsubscribeCount,!!F.subscribeButton.enabled,!!F.subscribeButton.classic,
F.channelId,!!F.subscribeButton.subscribed,V,C,k.player,!1);M.appendChild(V.element);k.W.push(V)}break;case "WEBSITE":k={U:"div",mN:["ytp-ce-element","ytp-ce-website"],L:{tabindex:"0","aria-label":F.us||"","aria-hidden":"true"},Y:[{U:"div",G:"ytp-ce-element-shadow"},{U:"div",G:"ytp-ce-expanding-overlay",Y:[{U:"div",G:"ytp-ce-expanding-overlay-hider"},{U:"div",G:"ytp-ce-expanding-overlay-background"},{U:"div",G:"ytp-ce-expanding-overlay-content",Y:[{U:"div",G:"ytp-ce-expanding-overlay-body",Y:[{U:"div",
G:"ytp-ce-expanding-overlay-body-padding",Y:[{U:"div",G:"ytp-ce-website-title",L:{dir:g.sd(F.title||"")},EO:F.title},{U:"div",G:"ytp-ce-website-metadata",EO:F.metadata},{U:"a",mN:["ytp-ce-website-goto","ytp-ce-link"],L:{href:IP(k,F.targetUrl),target:"_blank",tabindex:"-1"},EO:F.callToAction}]}]}]}]},{U:"div",G:"ytp-ce-expanding-image",L:T7(F)},{U:"div",G:"ytp-ce-expanding-icon",L:OzS(F.iconUrl)}]};a=new g.G(k);break;case "CREATOR_MERCHANDISE":a="",F.productPrice&&(a={U:"div",G:"ytp-ce-merchandise-price-container",
Y:[{U:"div",G:"ytp-ce-merchandise-price",EO:F.productPrice}]},F.additionalFeesText&&a.Y.push({U:"div",G:"ytp-ce-merchandise-additional-fees",EO:F.additionalFeesText})),k={U:"div",mN:["ytp-ce-element","ytp-ce-merchandise"],L:{tabindex:"0","aria-label":F.us||"","aria-hidden":"true"},Y:[{U:"div",G:"ytp-ce-element-shadow"},{U:"div",G:"ytp-ce-expanding-overlay",Y:[{U:"div",G:"ytp-ce-expanding-overlay-hider"},{U:"div",G:"ytp-ce-expanding-overlay-background"},{U:"div",G:"ytp-ce-expanding-overlay-content",
Y:[{U:"div",G:"ytp-ce-expanding-overlay-body",Y:[{U:"div",G:"ytp-ce-expanding-overlay-body-padding",Y:[{U:"div",G:"ytp-ce-merchandise-title",L:{dir:g.sd(F.title||"")},EO:F.title},a,{U:"div",G:"ytp-ce-merchandise-metadata",EO:F.metadata},{U:"a",mN:["ytp-ce-merchandise-goto","ytp-ce-link"],L:{href:IP(k,F.targetUrl),target:"_blank",tabindex:"-1"},EO:F.callToAction}]}]}]}]},{U:"div",G:"ytp-ce-expanding-image",L:T7(F)},{U:"div",G:"ytp-ce-merchandise-invideo-cta-container",Y:[{U:"div",G:"ytp-ce-merchandise-invideo-cta",
EO:F.callToAction||void 0}]}]},a=new g.G(k)}F.isPlaceholder&&g.Dz(a.element,"ytp-ce-placeholder");return a},Bkm=function(k,F,a){function V(){X(1)}
function M(){X(-1)}
F.listen("mouseenter",()=>{mD(k,F,a)});
F.listen("mouseleave",()=>{SN(k,F,a)});
k.player.S().K||F.listen("click",()=>{g.Dz(F.element,"ytp-ce-element-hover")});
F.listen("click",U=>{lCI(k,a,U)});
F.listen("keypress",U=>{lCI(k,a,U)});
F.listen("focus",()=>{mD(k,F,a)});
F.listen("blur",()=>{SN(k,F,a)});
F.listen("touchstart",()=>{mD(k,F,a)});
var C=g.ki("ytp-ce-expanding-overlay-hider",F.element);C&&F.N(C,"touchstart",U=>{U.stopPropagation();g.fa(F.element,"ytp-ce-element-hover");g.fa(F.element,"ytp-ce-force-expand")});
F.listen("keydown",U=>{k.I5=U.keyCode===9&&!U.shiftKey});
const X=U=>{k.T+=U;k.T>0?(g.Dz(F.element,"ytp-ce-force-expand"),Zx(k,a.id,!0)):(g.fa(F.element,"ytp-ce-force-expand"),g.fa(F.element,"ytp-ce-element-hover"),Zx(k,a.id,!1))};
C=U=>{U&&(F.listen("blur",()=>{U.style.display!="none"&&k.I5&&U.focus()}),F.N(U,"focus",V),F.N(U,"blur",M))};
C(g.ki("ytp-sb-subscribe",F.element));C(g.ki("ytp-sb-unsubscribe",F.element));F.listen("focus",V);F.listen("blur",M)},eN=function(k,F,a){function V(){C||(M++,M===F.length&&(X.stop(),a&&a()))}
if(!F||F.length===0||qY(k))a&&a();else{F=vBB(k,F);var M=0,C=!1,X=new g.La(()=>{C=!0;a&&a()},1E3,k);
X.start();for(k=0;k<F.length;k++)g.cP(F[k],V)}},T7=function(k){let F;
k.zs&&(F=k.zs.thumbnails);return OzS(F?F[F.length-1].url:null)},IP=function(k,F){k=k.player.S();
if(F){if(F.startsWith("//"))return k.protocol+":"+F;if(F.startsWith("/"))return g.S0(k)+F}else return"";return F},OzS=function(k){return k?{style:"background-image: url("+k+")"}:{}},mD=function(k,F,a){g.Np(F.element,"ytp-ce-element-hover")||(a.type==="VIDEO"||a.type==="PLAYLIST"?g.Dz(F.element,"ytp-ce-element-hover"):k.player.S().K?(new g.La(()=>{g.Dz(F.element,"ytp-ce-element-hover")},200)).start():g.Dz(F.element,"ytp-ce-element-hover"),eN(k,a.le),Zx(k,a.id,!0))},SN=function(k,F,a){g.fa(F.element,
"ytp-ce-element-hover");
g.fa(F.element,"ytp-ce-force-expand");Zx(k,a.id,!1)},lCI=function(k,F,a){if(F.targetUrl&&(!a||a.type!=="keypress"||a.keyCode===13)){for(var V=a.target;V&&!g.Np(V,"ytp-ce-element");){g.Np(V,"subscribe-label")&&dh(k,F);
if(g.Np(V,"ytp-ce-channel-subscribe"))return;V=V.parentElement||null}if(!V||g.Np(V,"ytp-ce-element-hover")){a.preventDefault();a.stopPropagation();if(V=k.K[F.id])SN(k,V,F),V.element.blur();if(a.ctrlKey||a.metaKey||F.Ej==="new")dh(k,F),k.player.sendVideoStatsEngageEvent(17,void 0),k.player.pauseVideo(),a=g.$g(IP(k,F.targetUrl)),a=g.LA(a),g.iJ(a,void 0,F.sessionData);else{const M=g.nE(k.player.S())||k.player.getVideoData().Ix,C=()=>{var X=IP(k,F.targetUrl),U=F.sessionData,y=F.watchEndpoint;const n=
g.yW(X);M&&n&&(n.v||n.list)?k.player.eq(n.v,U,n.list,!1,void 0,y||void 0):g.D6(X,U)};
dh(k,F,()=>{k.player.sendVideoStatsEngageEvent(17,C)})}}}},Zx=function(k,F,a){k.O&&(a?k.Z.show():k.Z.hide());
for(const V of Object.keys(k.K))V!==F&&g.B(k.K[V].element,"ytp-ce-element-shadow-show",a)},dh=function(k,F,a){eN(k,F.clickUrls,a);
(k=g.g4())&&F.kG&&g.zg(k,F.visualElement)},vBB=function(k,F){var a=k.player.getVideoData().clientPlaybackNonce;
k=k.player.getCurrentTime().toFixed(2);a={CPN:a,AD_CPN:a,MT:k};k=[];for(let V=0;V<F.length;V++)k.push(cSB(F[V],a));return k},cSB=function(k,F){return k.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,a=>{let V=unescape(a);
V=V.substring(1,V.length-1);return F[V]?escape(F[V]):a})},pZm=function(k){return typeof k==="string"?k:""},Pm=function(k,F,a){for(const V in F)if(F[V]===k)return k;
return a},Hm=function(k){if(!k)return null;
var F=g.$g(pZm(k.value));F=g.LA(F);if(!F)return null;const a=Pm(k.target,tIz,"current");if(a==null)k=null;else{var V=k.show_link_icon;k=new LQB(F,a,V==="true"||V==="false"?V==="true":!0,k.pause_on_navigation!=null?k.pause_on_navigation:!0)}return k},$Lm=function(k){if(!k)return null;
const F=Pm(k.type,Rzm),a=Pm(k.trigger,jmX);k=k.url;k=Array.isArray(k)&&k.length?k[0]:k;k=Hm(k?k:null);return F?new WQC(F,a,k):null},EBm=function(k,F){return g.sm(k.action,F)},Jg=function(k,F){k="background-image: url("+k+");";
const a=[];F&&a.push(F);return{U:"div",G:"iv-card-image",L:{style:k},Y:a}},rh=function(k){return k.customMessage?Qn("div","iv-card-message",k.customMessage):""},hg=function(k){if(!k.metaInfo||k.metaInfo.length===0)return"";
const F=[];for(const a of k.metaInfo)F.push(Qn("li","",a));return{U:"ul",G:"iv-card-meta-info",Y:F}},xq=function(k,F,a,V){if(V)for(const M of F)k.D(M,V,a.id,a.sessionData,a.hO.click,5)},Qn=function(k,F,a){F?typeof F==="string"?F={"class":F}:Array.isArray(F)&&(F={"class":F.join(" ")}):F={};
F.dir=g.sd(a);return{U:k,L:F,EO:a}},NkQ=function(k){if(!k.customMessage)return"";
const F=["iv-card-action","iv-card-primary-link"],a={};k.W5&&(F.push("iv-card-action-icon"),a.style="background-image: url("+k.W5+");");a.dir=g.sd(k.customMessage);const V=[{U:"span",EO:k.customMessage}];k.showLinkIcon&&(V.push("\u00a0"),V.push({U:"span",G:"iv-card-link-icon"}));return{U:"div",mN:F,L:a,Y:V}},DL8=function(k){var F;
(F=k)&&!(F=k.length>1?k.charAt(0)==="/"&&k.charAt(1)!=="/":k==="/")&&(F=k.replace(/^(https?:)?\/\//,"").split("/",1),F=!F||F.length<1||!F[0]?[]:F[0].toLowerCase().split(".").reverse(),F=F[0]==="com"&&F[1]==="youtube"||F[0]==="be"&&F[1]==="youtu");return F?k.indexOf("/redirect?")===-1:!1},izQ=function(k,F){return F?F:DL8(k)?"current":"new"},Ag=function(k,F,a,V,M,C,X){k.context.D.listen(F,"click",U=>{k.Ml(a,V,M,C||[],X||0,U)});
k.context.D.listen(F,"touchstart",()=>{k.vA=!1});
k.context.D.listen(F,"touchmove",()=>{k.vA=!0})},fCm=function(k){if(g.p(k,g.JP)?.url)return g.p(k,g.JP).url;
if((k=g.p(k,g.Mm))&&k.videoId){let F="/watch?v="+k.videoId;k.playlistId&&(F+="&list="+k.playlistId);k.index&&(F+="&index="+k.index);k.startTimeSeconds&&(F+="&t="+k.startTimeSeconds);return F}return null},Bm=function(k,F,a){return{OU:(k.impressionLoggingUrlsV2s||[]).map(V=>V.baseUrl||""),
click:(a.loggingUrls||[]).map(V=>V.baseUrl||""),
close:(F.dismissLoggingUrlsV2s||[]).map(V=>V.baseUrl||""),
Zk:(F.impressionLoggingUrlsV2s||[]).map(V=>V.baseUrl||""),
bZ:(F.clickLoggingUrlsV2s||[]).map(V=>V.baseUrl||"")}},vm=function(k,F){if(F.onClickCommand&&g.p(F.onClickCommand,g.EaQ)?.targetId==="engagement-panel-error-corrections"){k.j=F;
var a=!0}else a=!1;if(!a||zzS(k,F))if(a=G8X(k,F)){var V={wD:F,UP:a.element,nB:!1};if(F.onClickCommand)k.J.A("web_infocards_teaser_show_logging_fix")&&(k.E3||wZm(k),Yq(k,F.id),a=k.findLastIndex(V),g.eI(k.cards,a,0,V));else{k.isInitialized||bzz(k);Yq(k,F.id);const M=k.findLastIndex(V);g.eI(k.cards,M,0,V);a.rU(k.K,M);k.QX()}F.autoOpen?k.addCueRange(F.startMs,0x8000000000000,F.id,()=>{k.O||(k.D=V,Oi(k),kVX(k,V),lD(k,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(a=k.context.J.getCurrentTime()*1E3,a<5E3&&a>F.startMs&&
F0z(k,V),k.addCueRange(F.startMs,F.startMs+1,F.id,()=>{F0z(k,V)}),Oi(k))}},cm=function(k){k.O&&(k.n6.hide(),k.uw.K(),g.fa(k.context.J.getRootNode(),g.zv.IV_DRAWER_OPEN),k.O=!1,Vn(k.J),k.C&&k.C.stop(),k.C=new g.La(()=>{k.Jl&&(k.Jl.focus(),k.Jl=null)},330),k.C.start())},amk=function(k,F){F=F.data;
F.autoOpenMs&&k.addCueRange(F.autoOpenMs,0x8000000000000,"",()=>{lD(k,"YOUTUBE_DRAWER_AUTO_OPEN")});
F.autoCloseMs&&k.addCueRange(F.autoCloseMs,0x8000000000000,"",()=>{cm(k)});
const a=F.headerText;g.mm(k.Dl,a);k.Z&&(k.J.A("player_tooltip_data_title_killswitch")?k.Z.setAttribute("title",a):k.Z.setAttribute("data-tooltip-title",a));F.eventId&&(k.eventId=F.eventId);k.cA=g.nl(F.trackingParams);k.W=g.nl(F.closeTrackingParams);k.LL=g.nl(F.iconTrackingParams)},pJ=function(k,F,a){let V=-1,M=-1;
for(let C=0;C<k.length;C++){if(k[C].height===F||k[C].width===a)return k[C];((k[C].height||0)<F||(k[C].width||0)<a)&&(V<0||(k[V].height||0)<(k[C].height||0)||(k[V].width||0)<(k[C].width||0))?V=C:((k[C].height||0)>=F||(k[C].width||0)>=a)&&(M<0||(k[M].height||0)>(k[C].height||0)||(k[M].width||0)>(k[C].width||0))&&(M=C)}return k[M>=0?M:V]},tg=function(k,F,a,V){return{feature:a.feature?a.feature:"cards",
src_vid:k.context.videoData.videoId,annotation_id:F,ei:k.context.videoData.eventId||"",itct:V.trackingParams||""}},V2R=function(k,F){const a=F.cardId?F.cardId:`cr:${k.T}`;
var V=k.J.S().experiments.ql("enable_error_corrections_infocard_web_client");if(!F.content&&F.teaser.simpleCardTeaserRenderer&&V){V=F.teaser.simpleCardTeaserRenderer;var M=F.icon?F.icon.infoCardIconRenderer:null;if(V.channelAvatar&&V.channelAvatar.thumbnails&&V.channelAvatar.thumbnails.length>0)var C=pJ(V.channelAvatar.thumbnails,22,22).url;F={id:a,timestamp:k.T,type:"simple",teaserText:g.My(V.message),teaserDurationMs:Number(F.cueRanges[0].teaserDurationMs),startMs:Number(F.cueRanges[0].startCardActiveMs),
autoOpen:!!F.autoOpen,sessionData:{},sponsored:!1,hO:{},Lz:null,fR:V.trackingParams?g.nl(V.trackingParams):null,LL:M&&M.trackingParams?g.nl(M.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,W5:null,title:"",customMessage:"",url:null,onClickCommand:V.onTapCommand||null,oh:C};vm(k,F)}else if(F.content?.simpleCardContentRenderer){if(!F.cueRanges.length)return;C=F.content?.simpleCardContentRenderer;V=F.teaser.simpleCardTeaserRenderer;M=F.icon?F.icon.infoCardIconRenderer:null;F={id:a,
timestamp:k.T,type:"simple",teaserText:g.My(V.message),teaserDurationMs:Number(F.cueRanges[0].teaserDurationMs),startMs:Number(F.cueRanges[0].startCardActiveMs),autoOpen:!!F.autoOpen,sessionData:tg(k,a,F,C),sponsored:!1,hO:Bm(C,V,C.command),Lz:C.trackingParams?g.nl(C.trackingParams):null,fR:V.trackingParams?g.nl(V.trackingParams):null,LL:M&&M.trackingParams?g.nl(M.trackingParams):null,imageUrl:pJ(C.image.thumbnails,290,290).url,displayDomain:C.displayDomain?g.My(C.displayDomain):null,showLinkIcon:!!C.showLinkIcon,
W5:null,title:C.title?g.My(C.title):"",customMessage:C.callToAction?g.My(C.callToAction):"",url:g.p(C.command,g.JP).url?Hm({pause_on_navigation:!k.context.videoData.isLivePlayback,target:"new",value:g.p(C.command,g.JP).url}):null,onClickCommand:null};vm(k,F)}else if(F.content?.collaboratorInfoCardContentRenderer){if(!F.cueRanges.length)return;C=F.content?.collaboratorInfoCardContentRenderer;V=F.teaser.simpleCardTeaserRenderer;M=F.icon?F.icon.infoCardIconRenderer:null;F={id:a,timestamp:k.T,type:"collaborator",
teaserText:g.My(V.message),teaserDurationMs:Number(F.cueRanges[0].teaserDurationMs),startMs:Number(F.cueRanges[0].startCardActiveMs),autoOpen:!!F.autoOpen,sessionData:tg(k,a,F,C),sponsored:!1,hO:Bm(C,V,C.endpoint),Lz:C.trackingParams?g.nl(C.trackingParams):null,fR:V.trackingParams?g.nl(V.trackingParams):null,LL:M&&M.trackingParams?g.nl(M.trackingParams):null,channelId:g.p(C.endpoint,g.VA).browseId,customMessage:C.customText?g.My(C.customText):null,profileImageUrl:pJ(C.channelAvatar.thumbnails,290,
290).url,title:C.channelName?g.My(C.channelName):"",metaInfo:[C.subscriberCountText?g.My(C.subscriberCountText):""],url:Hm({pause_on_navigation:!k.context.videoData.isLivePlayback,target:"new",value:g.p(C.endpoint,g.VA).canonicalBaseUrl?g.p(C.endpoint,g.VA).canonicalBaseUrl:`/channel/${g.p(C.endpoint,g.VA).browseId}`}),onClickCommand:null};vm(k,F)}else if(F.content?.playlistInfoCardContentRenderer){if(!F.cueRanges.length)return;C=F.content?.playlistInfoCardContentRenderer;V=F.teaser.simpleCardTeaserRenderer;
M=F.icon?F.icon.infoCardIconRenderer:null;F={id:a,timestamp:k.T,type:"playlist",teaserText:g.My(V.message),teaserDurationMs:Number(F.cueRanges[0].teaserDurationMs),startMs:Number(F.cueRanges[0].startCardActiveMs),autoOpen:!!F.autoOpen,sessionData:tg(k,a,F,C),sponsored:!1,hO:Bm(C,V,C.action),Lz:C.trackingParams?g.nl(C.trackingParams):null,fR:V.trackingParams?g.nl(V.trackingParams):null,LL:M&&M.trackingParams?g.nl(M.trackingParams):null,mZ:pJ(C.playlistThumbnail.thumbnails,258,290).url,customMessage:C.customMessage?
g.My(C.customMessage):null,playlistVideoCount:g.My(C.playlistVideoCount),title:C.playlistTitle?g.My(C.playlistTitle):"",metaInfo:[C.channelName?g.My(C.channelName):"",C.videoCountText?g.My(C.videoCountText):""],url:Hm({pause_on_navigation:!k.context.videoData.isLivePlayback,target:"new",value:fCm(C.action)}),onClickCommand:null};vm(k,F)}else if(F.content?.videoInfoCardContentRenderer){if(!F.cueRanges.length)return;C=F.content?.videoInfoCardContentRenderer;V=F.teaser.simpleCardTeaserRenderer;M=F.icon?
F.icon.infoCardIconRenderer:null;F={id:a,timestamp:k.T,type:"video",teaserText:g.My(V.message),teaserDurationMs:Number(F.cueRanges[0].teaserDurationMs),startMs:Number(F.cueRanges[0].startCardActiveMs),autoOpen:!!F.autoOpen,sessionData:tg(k,a,F,C),sponsored:!1,hO:Bm(C,V,C.action),Lz:C.trackingParams?g.nl(C.trackingParams):null,fR:V.trackingParams?g.nl(V.trackingParams):null,LL:M&&M.trackingParams?g.nl(M.trackingParams):null,mZ:pJ(C.videoThumbnail.thumbnails,258,290).url,videoDuration:C.lengthString?
g.My(C.lengthString):null,customMessage:C.customMessage?g.My(C.customMessage):null,title:C.videoTitle?g.My(C.videoTitle):"",metaInfo:[C.channelName?g.My(C.channelName):"",C.viewCountText?g.My(C.viewCountText):""],isLiveNow:!!C.badge,url:Hm({pause_on_navigation:!k.context.videoData.isLivePlayback,target:"new",value:fCm(C.action)}),onClickCommand:null};vm(k,F)}k.T++},M2Q=function(k,F){return g.sm(k.cards,a=>a.wD.id===F)},Oi=function(k){g.B(k.J.getRootNode(),"ytp-cards-shopping-active",CfC(k))},Yq=function(k,
F){if(F=M2Q(k,F))F===k.D&&(k.D=null),k.J.removeCueRange(F.wD.id),g.TJ(F.UP),g.qL(k.cards,F),k.QX(),Oi(k)},lD=function(k,F,a){if(!k.O){k.n6.show();
k.TL=new g.La(()=>{g.Dz(k.context.J.getRootNode(),g.zv.IV_DRAWER_OPEN)},0);
k.TL.start();k.uw.N(k.K,"mousewheel",M=>{k.VX.start();M.preventDefault();M=M||window.event;let C=0;M.type=="MozMousePixelScroll"?C=0==(M.axis==M.HORIZONTAL_AXIS)?M.detail:0:window.opera?C=M.detail:C=M.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?M.wheelDeltaY/-30:M.wheelDeltaY/-1.2:M.wheelDelta/-1.6:M.wheelDeltaY/-3;if(M=C)k.K.scrollTop+=M});
k.O=!0;var V=g.g4();V&&k.cA&&k.W&&g.is(V,[k.cA,k.W]);F={TRIGGER_TYPE:F};for(const M of k.cards)M.nB||(M.nB=!0,spI(k.context.logger,M.wD.hO.OU,F)),V&&g.is(V,[M.wD.Lz]);Vn(k.J);a&&(k.C=new g.La(()=>{k.Jl=k.Z;k.yX.focus()},330),k.C.start())}},bzz=function(k){g.iP(k.Zl(),[g.zv.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.Ii(k.J,k.V,5);k.X5();k.Z=g.ki("ytp-cards-button",k.J.getRootNode());k.yX=g.ki("iv-drawer-close-button",k.V);k.isInitialized=!0},wZm=function(k){k.I5.push(g.G0("iv-teaser-shown",k.uI,k));
k.I5.push(g.G0("iv-teaser-hidden",k.Eu,k));k.I5.push(g.G0("iv-teaser-clicked",k.gB,k));k.E3=!0},zzS=function(k,F){k.j=F;
var a=k.J.getVideoData();if(!a)return!1;a=g.Rf(a);if(a?.markersMap)for(let M=0;a?.markersMap.length>M;M++){var V=a?.markersMap[M];if(V.key==="ERROR_CORRECTION_MARKERS"&&(V=V.value?.markers)&&V.length>0)return F.startMs=g.p(V[0],g.Hmw)?.timeRangeStartMillis||0,k.j=null,!0}return!1},G8X=function(k,F){switch(F.type){case "simple":k=k.OO;
var a=F.displayDomain?{U:"div",G:"iv-card-image-text",EO:F.displayDomain}:void 0;var V=NkQ(F);a={U:"div",mN:["iv-card"],Y:[{U:"a",G:"iv-click-target",L:{href:F.url?F.url.D()||"":""},Y:[Jg(F.imageUrl,a),{U:"div",G:"iv-card-content",Y:[Qn("h2",void 0,F.title),V]}]}]};a=new g.G(a);xq(k,g.bL("iv-click-target",a.element),F,F.url);F=a;break;case "collaborator":k=k.OO;a={U:"div",mN:["iv-card","iv-card-channel"],Y:[{U:"a",mN:["iv-click-target"],L:{href:F.url.D()||"","data-ytid":F.channelId},Y:[Jg(F.profileImageUrl),
{U:"div",G:"iv-card-content",Y:[rh(F),{U:"h2",G:"iv-card-primary-link",EO:F.title},hg(F)]}]}]};a=new g.G(a);xq(k,g.bL("iv-click-target",a.element),F,F.url);F=a;break;case "playlist":k=k.OO;a={U:"div",mN:["iv-card","iv-card-playlist"],Y:[{U:"a",G:"iv-click-target",L:{href:F.url.D()||""},Y:[Jg(F.mZ,{U:"div",G:"iv-card-image-overlay",Y:[{U:"span",G:"iv-card-playlist-video-count",EO:F.playlistVideoCount}]}),{U:"div",G:"iv-card-content",Y:[rh(F),Qn("h2","iv-card-primary-link",F.title),hg(F)]}]}]};a=new g.G(a);
xq(k,g.bL("iv-click-target",a.element),F,F.url);F=a;break;case "productListing":k=k.OO;var M=F.offers.length!=0;a=["iv-card"];V="";var C=NkQ(F);M&&(a.push("iv-card-product-listing"),V="iv-card-primary-link",C=F.offers[0],M=[],C.price&&M.push({U:"div",G:"iv-card-offer-price",EO:C.price}),C.merchant&&M.push({U:"div",G:"iv-card-offer-merchant",EO:C.merchant}),C={U:"div",Y:M});M=F.url?F.url.D()||"":"";a={U:"div",mN:a,L:{tabindex:"0"},Y:[{U:"a",mN:["iv-card-image","iv-click-target"],L:{style:"background-image: url("+
F.imageUrl+");",href:M,"aria-hidden":"true",tabindex:"-1"}},{U:"div",G:"iv-card-content",Y:[F.sponsored?{U:"div",G:"iv-card-sponsored",Y:["Sponsored",{U:"div",G:"iv-ad-info-container",Y:[{U:"div",G:"iv-ad-info",EO:"{{adInfo}}"},{U:"div",G:"iv-ad-info-icon-container",Y:[{U:"div",G:"iv-ad-info-icon"},{U:"div",G:"iv-ad-info-callout"}]}]}]}:"",{U:"a",G:"iv-click-target",L:{href:M},Y:[Qn("h2",V,F.title),C]}]}]};a=new g.G(a);V=g.nR("span");g.mm(V,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
a.setContent(V,"adInfo");xq(k,g.bL("iv-click-target",a.element),F,F.url);F=a;break;case "video":k=k.OO;a=F.isLiveNow?{U:"span",mN:["yt-badge","yt-badge-live"],EO:"LIVE NOW"}:null;a={U:"div",mN:["iv-card","iv-card-video"],Y:[{U:"a",G:"iv-click-target",L:{href:F.url?.D()||""},Y:[Jg(F.mZ,F.videoDuration?{U:"span",G:"iv-card-video-duration",EO:F.videoDuration}:void 0),{U:"div",G:"iv-card-content",Y:[rh(F),Qn("h2","iv-card-primary-link",F.title),hg(F),a]}]}]};a=new g.G(a);xq(k,g.bL("iv-click-target",a.element),
F,F.url);F=a;break;default:return null}return F},F0z=function(k,F){if(!g.Np(k.J.getRootNode(),"ytp-cards-teaser-shown")){if(k.D!==F){var a=g.g4(),V=k.D?k.D.wD.LL:k.LL;
a&&V&&g.fl(a,[V]);k.D=F;Oi(k)}(a=k.isInitialized&&k.Zl().style.display=="none")||(a=k.context.J.getPlayerState(),V=a===0&&k.context.J.getCurrentTime()===0,a=!(a===1||a===3||V));a||F.wD.teaserDurationMs&&k.J.wM(!0,{teaserText:F.wD.teaserText,durationMs:F.wD.teaserDurationMs,onClickCommand:F.wD.onClickCommand,oh:F.wD.oh??null});k.Yw.isActive()||((!k.O||!k.VX.isActive()&&k.a5)&&kVX(k,F),k.Yw.start(910+F.wD.teaserDurationMs))}},CfC=function(k){return k.D?k.D.wD.type==="productListing":k.J.A("enable_wn_infocards")?
!!k.cards?.length&&g.ML(k.cards,F=>F.wD.type==="productListing"):g.ML(k.cards,F=>F.wD.type==="productListing")},kVX=function(k,F){k.X.Vm?(F=new Ui([0,
k.K.scrollTop],[0,F.UP.offsetTop],600,Qmz),k.context.O.listen(F,"animate",a=>{k.K.scrollTop=a.y}),k.context.O.listen(F,"finish",a=>{k.K.scrollTop=a.y}),F.play()):(k.X.Sd(!0),k.K.scrollTop=F.UP.offsetTop,k.X.Sd(!1))},LJ=function(k){return k.D&&k.D.wD?k.D.wD:k.cards[0]&&k.cards[0].wD?k.cards[0].wD:null},XYX=function(k){const F=k.annotation.data;
"start_ms"in F&&"end_ms"in F&&k.addCueRange(Number(F.start_ms),Number(F.end_ms),k.annotation.id,()=>{k.show()},()=>{k.hide()})},UKR=function(k,F){var a=mLB(F).width;
g.N$(F,a);a=new oP(F,[a,F.offsetTop],[a-a,F.offsetTop],200,JSk);g.Q(k,a);k.context.O.listen(a,"begin",()=>{g.Fg(F,!0)});
a.play()},RP=function(k,F,a){a.stopPropagation();
yB7(k);ogB(k,F);k.D.focus()},ngX=function(k){const F=k.annotation.data;
if(k.annotation.style==="cta")var a=6;else if(k.annotation.style==="video"||k.annotation.style==="playlist")a=7;k.C=F.collapsedelay_ms||k.C;const V=["iv-promo","iv-promo-inactive"];k.Zl().setAttribute("aria-hidden","true");k.Zl().setAttribute("aria-label","Promotion");k.Zl().tabIndex=0;const M=k.annotation.Rx();let C;var X=F.image_url;X&&(C=k.createElement({U:"div",mN:["iv-promo-img","iv-click-target"]}),X=k.createElement({U:"img",L:{src:X,"aria-hidden":"true"}}),C.appendChild(X),F.video_duration&&
!F.is_live?(X=k.createElement({U:"span",G:"iv-promo-video-duration",EO:F.video_duration}),C.appendChild(X)):F.playlist_length&&(X=k.createElement({U:"span",G:"iv-promo-playlist-length",EO:F.playlist_length.toString()}),C.appendChild(X)),M&&Ag(k,C,M,k.annotation.id,F.session_data,void 0,a));M?(X=k.createElement({U:"a",G:"iv-promo-txt"}),g.Dm(X,M.D()),k.D=X):k.D=k.createElement({U:"div",G:"iv-promo-txt"});let U,y,n,u;switch(k.annotation.style){case "cta":case "website":U=k.createElement({U:"p",Y:[{U:"strong",
EO:F.text_line_1}]});y=k.createElement({U:"p",Y:[{U:"span",G:"iv-promo-link",EO:F.text_line_2}]});if(X=F.text_line_3)V.push("iv-promo-website-card-cta-redesign"),n=k.createElement({U:"button",mN:["iv-promo-round-expand-icon","ytp-button"]}),X=k.createElement({U:"button",mN:["iv-button","iv-promo-button"],Y:[{U:"span",G:"iv-button-content",EO:X}]}),u=k.createElement({U:"div",G:"iv-promo-button-container"}),u.appendChild(X),M&&Ag(k,k.Zl(),M,k.annotation.id,F.session_data,void 0,a);g.Dz(k.D,"iv-click-target");
M&&Ag(k,k.D,M,k.annotation.id,F.session_data,void 0,a);break;case "playlist":case "video":U=k.createElement({U:"p",Y:[{U:"span",EO:F.text_line_1}]}),y=k.createElement({U:"p",Y:[{U:"strong",EO:F.text_line_2}]}),F.is_live&&(U=y,y=k.createElement({U:"span",mN:["yt-badge","iv-promo-badge-live"],EO:"LIVE NOW"})),g.Dz(k.D,"iv-click-target"),M&&Ag(k,k.D,M,k.annotation.id,F.session_data,void 0,a),V.push("iv-promo-video")}U&&k.D.appendChild(U);y&&k.D.appendChild(y);k.T.appendChild(k.D);u&&k.T.appendChild(u);
a=k.createElement({U:"div",G:"iv-promo-actions"});k.K=k.createElement({U:"button",mN:["iv-promo-expand","ytp-button"]});k.K.title="Expand";k.context.D.listen(k.K,"click",K=>{RP(k,5E3,K)});
a.appendChild(k.K);g.Fg(k.K,!1);k.context.D.listen(k.Zl(),"mouseover",k.VX,k);k.context.D.listen(k.Zl(),"mouseout",k.OO,k);k.context.D.listen(k.Zl(),"touchend",K=>{RP(k,5E3,K)});
k.O=k.createElement({U:"button",mN:["iv-promo-close","ytp-button"]});k.O.title="Close";k.context.D.listen(k.O,"click",k.annotation.style==="cta"&&F.text_line_3?k.j:k.I5,k);a.appendChild(k.O);g.iP(k.Zl(),V);C&&(g.KR(k.Zl(),C),n&&C.appendChild(n));g.KR(k.Zl(),k.T);g.KR(k.Zl(),a)},jN=function(k){k.V&&(g.Tm.clearTimeout(k.V),k.V=null)},yB7=function(k){k.Z.stop();
k.isCollapsed&&(g.zX(k.Zl(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),k.isCollapsed=!1,k.D&&k.D.removeAttribute("aria-hidden"),g.Fg(k.K,!1),g.Fg(k.O,!0))},ogB=function(k,F){k.V||(k.V=g.Gn(function(){jN(this);
uvz(this)},F,k))},uvz=function(k){k.isCollapsed||k.W||k.V||(g.Dz(k.Zl(),"iv-promo-collapsed"),k.isCollapsed=!0,k.Z.start())},spI=function(k,F,a){F&&(a?Wm(k,F.map(V=>g.Zz(V,a))):Wm(k,F))},Wm=function(k,F,a,V){let M=1,C=void 0,X=-1;
if(a){let U=!1;C=()=>{M--;M||U||(clearTimeout(X),U=!0,a())};
X=setTimeout(()=>{U=!0;a()},1E3)}for(const U of F||[])M++,g.cP(U,C);
V&&(M++,V!==0&&k.J.sendVideoStatsEngageEvent(V,C))},K0k=function(k){return k==="annotation-editor"||k==="live-dashboard"},qHC=function(k){k.V&&(k.player.removeEventListener("videodatachange",k.V),k.V=null)},ggC=function(k){k=k.createElement({U:"div",
mN:["annotation","annotation-type-custom"]});g.Fg(k,!1);return k},Ei=function(k,F){var a=!1,V=F.getElementsByTagName("annotations");
if(V&&!(V.length<1)&&(V=V[0].getAttribute("itct"))){var M=g.g4();if(M){var C=g.qi();C&&g.FN(g.pl)(void 0,M,C,[g.nl(V)])}}F=F.getElementsByTagName("annotation");for(V=0;V<F.length;V++){var X=ToS(k,F[V]);M=null;try{a:{if(!X){M=null;break a}var U=X.id;C=/.+/;const T=typeof U==="string"&&C!=null&&U!=null&&U.match(C)?U:"",S=Pm(X.type,ImL),J=Pm(X.style,mKz),x=pZm(X.data),O=x.length!==0?JSON.parse(x):{};b:{var y=X.action;C=$Lm;if(y==null){var n=null;break b}if(g.P1(y)){X=[];for(const l of y){const t=C(l);
t&&X.push(t)}n=X;break b}const A=C(y);n=A?[A]:[]}C=n;M=T&&S?new SHL(T,S,J,C,O):null}}catch(T){}if(M)if(M.type==="branding"||M.type==="promotion"){C=k;X=M;var u=ggC(C),K=null;switch(X.type){case "branding":if(C.player.S().Ra)break;C.player.A("web_player_overlay_positioned_layout")?(u.setAttribute("data-overlay-order","11"),C.player.cY(u,4,!0)):C.K.element.appendChild(u);K=new ZAX(u,$q(C),X);break;case "promotion":g.Ii(C.player,u,4),K=new ebk(u,$q(C),X)}K&&K.D3();if(C=K)g.Q(k,C),k.C[M.id]=C}else if(M.type===
"card"||M.type==="drawer"){k.D||(k.D=dK8(k),g.Q(k,k.D));if(M.type==="card"){u=k.D;var q=(a=M)&&a.data&&a.data.card_type;M=a.data;if(q)switch(C=M.tracking||{},C={OU:C.impression,click:C.click,close:C.close,Zk:C.teaser_impression,bZ:C.teaser_click},X=M.tracking_params||{},K=null,q){case "collaborator":a={id:a.id,timestamp:M.timestamp||0,type:M.card_type,teaserText:M.teaser_text,teaserDurationMs:M.teaser_duration_ms,startMs:M.start_ms,autoOpen:M.auto_open||!1,sessionData:M.session_data||{},sponsored:M.sponsored||
!1,hO:C,Lz:X.card?g.nl(X.card):null,fR:X.teaser?g.nl(X.teaser):null,LL:X.icon?g.nl(X.icon):null,channelId:M.channel_id,customMessage:M.custom_message?M.custom_message:null,profileImageUrl:M.image_url,title:M.title,metaInfo:M.meta_info,url:Hm({pause_on_navigation:M.pause_on_navigation,target:M.target||"new",value:M.url}),onClickCommand:null};vm(u,a);break;case "playlist":a={id:a.id,timestamp:M.timestamp||0,type:M.card_type,teaserText:M.teaser_text,teaserDurationMs:M.teaser_duration_ms,startMs:M.start_ms,
autoOpen:M.auto_open||!1,sessionData:M.session_data||{},sponsored:M.sponsored||!1,hO:C,Lz:X.card?g.nl(X.card):null,fR:X.teaser?g.nl(X.teaser):null,LL:X.icon?g.nl(X.icon):null,mZ:M.image_url,playlistVideoCount:M.playlist_video_count,customMessage:M.custom_message?M.custom_message:null,title:M.title,metaInfo:M.meta_info,url:Hm({pause_on_navigation:M.pause_on_navigation,target:M.target||"new",value:M.url}),onClickCommand:null};vm(u,a);break;case "productListing":M.signin_url&&(K=Hm({target:"current",
value:M.signin_url}));q=[];const T=M.offers||[];for(let S=0;S<T.length;S++)q.push(new PfB(g.TI(T[S].merchant),g.TI(T[S].price)));a={id:a.id,timestamp:M.timestamp||0,type:M.card_type,teaserText:M.teaser_text,teaserDurationMs:M.teaser_duration_ms,startMs:M.start_ms,autoOpen:M.auto_open||!1,sessionData:M.session_data||{},sponsored:M.sponsored||!1,hO:C,Lz:X.card?g.nl(X.card):null,fR:X.teaser?g.nl(X.teaser):null,LL:X.icon?g.nl(X.icon):null,imageUrl:M.image_url,displayDomain:M.display_domain?M.display_domain:
null,showLinkIcon:!!M.show_link_icon,W5:M.button_icon_url?M.button_icon_url:null,title:M.title,customMessage:M.custom_message?M.custom_message:null,url:Hm({pause_on_navigation:M.pause_on_navigation,target:M.target||"new",value:M.url}),pJL:K,ELF:M.signin_title?M.signin_title:void 0,O$l:M.signin_message?M.signin_message:void 0,offers:q,onClickCommand:null};vm(u,a);break;case "simple":a={id:a.id,timestamp:M.timestamp||0,type:M.card_type,teaserText:M.teaser_text,teaserDurationMs:M.teaser_duration_ms,
startMs:M.start_ms,autoOpen:M.auto_open||!1,sessionData:M.session_data||{},sponsored:M.sponsored||!1,hO:C,Lz:X.card?g.nl(X.card):null,fR:X.teaser?g.nl(X.teaser):null,LL:X.icon?g.nl(X.icon):null,imageUrl:M.image_url,displayDomain:M.display_domain?M.display_domain:null,showLinkIcon:!!M.show_link_icon,W5:M.button_icon_url?M.button_icon_url:null,title:M.title,customMessage:M.custom_message?M.custom_message:null,url:Hm({pause_on_navigation:M.pause_on_navigation,target:M.target||"new",value:M.url}),onClickCommand:null};
vm(u,a);break;case "video":a={id:a.id,timestamp:M.timestamp||0,type:M.card_type,teaserText:M.teaser_text,teaserDurationMs:M.teaser_duration_ms,startMs:M.start_ms,autoOpen:M.auto_open||!1,sessionData:M.session_data||{},sponsored:M.sponsored||!1,hO:C,Lz:X.card?g.nl(X.card):null,fR:X.teaser?g.nl(X.teaser):null,LL:X.icon?g.nl(X.icon):null,mZ:M.image_url,videoDuration:M.video_duration||null,customMessage:M.custom_message?M.custom_message:null,title:M.title,metaInfo:M.meta_info,isLiveNow:!!M.is_live_now,
url:Hm({pause_on_navigation:M.pause_on_navigation,target:M.target||"new",value:M.url}),onClickCommand:null},vm(u,a)}}else amk(k.D,M);a=!0}}a&&(Vn(k.player),k.X())},HAz=function(k){const F=k.player.S();
k=k.player.getVideoData();return(F.annotationsLoadPolicy||k.annotationsLoadPolicy)===1&&!k.xu||F.cA.get(k.videoId)||k.KJ()||g.t0(k)?!0:!1},JBz=function(k,F){F=!F.isCued()&&!F.D(1024);
k.K.Sd(F);k.O.Sd(F)},xKC=function(k,F){const a=F.videoId;
var V=C=>{var X=k.loadNumber;k.T=null;k.loaded&&k.loadNumber===X&&k.player.getVideoData().videoId===a&&(C=g.PM(C)&&C.responseXML?C.responseXML:null)&&(Ei(k,C),g.Dz(k.player.getRootNode(),"iv-module-loaded"))};
g.g7()&&(V=QpI(k,V));const M={format:"XML",onFinish:V,onError:()=>{k.T=null},
urlParams:{}};F.isPharma&&(M.urlParams.pharma="1");M.method="POST";M.withCredentials=!0;(V=k.player.S().cA.get(a))&&rBk(M,V);V=V&&V.rS;if(!F.DR||V)k.V=()=>{if(!k.j)k.onVideoDataChange(M);const C=k.player.getVideoData();C?.Fm()&&!k.I5&&hb7(k,C)},k.player.addEventListener("videodatachange",k.V)},NY=function(k,F){var a=!1;
k.D||(k.D=dK8(k),g.Q(k,k.D));for(var V of F.cards||[])V.cardRenderer&&(V2R(k.D,V.cardRenderer),a=!0);a&&(k.player.getVideoData()?.Fm()||(a=k.D,V=F.headerText?g.My(F.headerText):"",g.mm(a.Dl,V),a.Z&&(a.J.A("player_tooltip_data_title_killswitch")?a.Z.setAttribute("title",V):a.Z.setAttribute("data-tooltip-title",V)),a.context.videoData.eventId&&(a.eventId=a.context.videoData.eventId),a.cA=F.trackingParams?g.nl(F.trackingParams):null,a.W=F.closeButton.infoCardIconRenderer.trackingParams?g.nl(F.closeButton.infoCardIconRenderer.trackingParams):
null,a.LL=F.icon.infoCardIconRenderer.trackingParams?g.nl(F.icon.infoCardIconRenderer.trackingParams):null,k.X()),Vn(k.player))},hb7=function(k,F){if(F=F.getWatchNextResponse()?.cards?.cardCollectionRenderer)k.I5=!0,NY(k,F),F.headerText&&k.TV&&(F=g.My(F.headerText),k.player.A("player_tooltip_data_title_killswitch")?k.TV.setAttribute("title",F):k.TV.setAttribute("data-tooltip-title",F))},QpI=function(k,F){return(...a)=>{k.wU()||k.D3.push(g.xH.NZ(()=>{F(...a)}))}},rBk=function(k,F){k.method="POST";
k.postParams=k.postParams||{};F.rS&&(k.postParams.ic_coll=F.rS);F.Cx&&(k.postParams.ic_track=F.Cx)},ToS=function(k,F){const a={};
for(var V of F.attributes)a[V.name]=V.nodeValue;for(V=0;V<F.childNodes.length;V++){var M=F.childNodes[V];if(!g.H1(M)||M.nodeType!=1)continue;var C=void 0;if(a[M.tagName])C=a[M.tagName];else if(M.tagName==="data"){M.childNodes.length>0&&(C=M.childNodes[0].nodeValue,a[M.tagName]=typeof C==="string"?C.trim():C);continue}else C=[],a[M.tagName]=C;M&&M.tagName==="TEXT"?M.childNodes.length===1&&M.childNodes[0].nodeType===3?C.push(M.childNodes[0].nodeValue):C.push(""):M&&C.push(ToS(k,M))}return a},$q=function(k){if(!k.W){const F=
new AB8(k);
g.Q(k,F);const a=new g.kH(k);g.Q(k,a);k.W=new Boz(F,a,k.player.S(),k.player.getVideoData(),k.logger,k.player,k.bP)}return k.W},YHL=function(k){const F=k.player.getVideoData();
if(F.t$){var a=k.player.S().cA.get(F.videoId);if(a){var V={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:(M,C,X)=>{M=k.loadNumber;C=F.videoId;k.loaded&&k.loadNumber===M&&k.player.getVideoData().videoId===C&&(X=g.PM(X)&&X.responseXML?X.responseXML:null)&&Ei(k,X)}};
g.g7()&&(V.onFinish=QpI(k,V.onFinish));V.postParams={ic_only:"1"};rBk(V,a);k.j=!0;g.vM(F.t$,V)}}},dK8=function(k){const F=new g.G({U:"div"});
g.Fg(F.element,!1);const a=new OA7(k.player,F.element,$q(k));g.Q(a,F);F.rU(k.K.element);a.D3();return a},lmI=function(k,F,a,V,M){if(!k.player.S().Ra){var C=[];
F.navigationEndpoint&&g.p(F.navigationEndpoint,g.VA)&&g.p(F.navigationEndpoint,g.VA).browseId&&C.push(new WQC("openUrl","click",new LQB(`/channel/${g.p(F.navigationEndpoint,g.VA).browseId}`,"new",!0,!0)));var X=F.watermark.thumbnails[0];V={channel_name:F.channelName,end_ms:F.endTimeMs,image_height:X.height,image_type:1,image_url:X.url,image_width:X.width,is_mobile:!1,session_data:{annotation_id:a,ei:M,feature:"iv",itct:F.trackingParams,src_vid:V},start_ms:F.startTimeMs};if(F.subscribeButton&&g.p(F.subscribeButton,
g.gE)){V.channel_id=g.p(F.subscribeButton,g.gE).channelId;F=g.p(F.subscribeButton,g.gE);X=M=null;F.subscribed?(F.subscriberCountWithUnsubscribeText&&(M=g.My(F.subscriberCountWithUnsubscribeText)),F.subscriberCountText&&(X=g.My(F.subscriberCountText))):(F.subscriberCountText&&(M=g.My(F.subscriberCountText)),F.subscriberCountWithSubscribeText&&(X=g.My(F.subscriberCountWithSubscribeText)));const U=g.p(F.signInEndpoint?.commandMetadata,g.Xt)?.url||"";F={subscribeText:g.My(F.unsubscribedButtonText),subscribeCount:M||
"",unsubscribeText:g.My(F.subscribedButtonText),unsubscribeCount:X||"",enabled:F.enabled||!1,classic:!1,subscribed:F.subscribed||!1,feature:"iv",signInUrl:U};V.standalone_subscribe_button_data=F}C=new SHL(a,"branding","branding",C,V);V=ggC(k);k.player.A("web_player_overlay_positioned_layout")?(V.setAttribute("data-overlay-order","11"),k.player.cY(V,4,!0)):k.K.element.appendChild(V);C=new ZAX(V,$q(k),C);C.D3();g.Q(C,C);k.C[a]=C}};
g.f3.prototype.wM=g.aH(36,function(k,F){const a=g.hy(this.cB());a&&a.wM(k,F)});
var CJ={},si=null;g.Yp(Ui,g.bP);g.H=Ui.prototype;g.H.getDuration=function(){return this.duration};
g.H.play=function(k){if(k||this.D==0)this.progress=0,this.coords=this.K;else if(this.isPlaying())return!1;Xo(this);this.startTime=k=g.xp();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.V=this.startTime;this.progress||this.XU();this.M8("play");this.isPaused()&&this.M8("resume");this.D=1;const F=g.QX(this);F in CJ||(CJ[F]=this);ezm();dLS(this,k);return!0};
g.H.stop=function(k){Xo(this);this.D=0;k&&(this.progress=1);PR8(this,this.progress);this.onStop();this.ji()};
g.H.pause=function(){this.isPlaying()&&(Xo(this),this.D=-1,this.M8("pause"))};
g.H.p6=function(){this.D==0||this.stop(!1);this.M8("destroy");Ui.dD.p6.call(this)};
g.H.destroy=function(){this.dispose()};
g.H.wd=function(){this.M8("animate")};
g.H.M8=function(k){this.dispatchEvent(new HzS(k,this))};
g.Yp(HzS,g.wF);g.Yp(yn,Ui);yn.prototype.O=function(){};
yn.prototype.wd=function(){this.O();yn.dD.wd.call(this)};
yn.prototype.ji=function(){this.O();yn.dD.ji.call(this)};
yn.prototype.XU=function(){this.O();yn.dD.XU.call(this)};
g.Yp(oP,yn);oP.prototype.O=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};var AB8=class extends g.GB{constructor(k){super();this.K=k||window;this.D=[]}listen(k,F,a,V){a=(0,g.ry)(a,V||this.K);k=g.jY(k,F,a);this.D.push(k);return k}wj(k,F,a,V){a=(0,g.ry)(a,V||this.K);k=Smz(k,F,a);this.D.push(k);return k}Ar(k){g.Wd(k);g.qL(this.D,k)}removeAll(){g.Wd(this.D);this.D.length=0}p6(){this.removeAll();super.p6()}};var L0S=class extends g.ZH{constructor(k){super(k);this.V=this.endscreen=null;this.K={};this.C={};this.Z=this.O=null;this.W=[];this.D=null;this.I5=!0;this.T=0;k=k.S();this.X=g.GM(k)||g.Fd(k);this.events=new g.Ms(this);g.Q(this,this.events);this.events.N(this.player,g.oO("creatorendscreen"),this.onCueRangeEnter);this.events.N(this.player,g.nX("creatorendscreen"),this.onCueRangeExit);this.events.N(this.player,"resize",this.jd);this.events.N(window,"focus",this.j);this.load();const F=g.nR("STYLE");(g.GI("HEAD")[0]||
document.body).appendChild(F);this.addOnDisposeCallback(()=>{g.TJ(F)});
F.sheet&&(F.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),F.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))}load(){super.load();if(!qY(this)){var k=g.JOB(this.player.getVideoData());k?(k=KJ(k,hz7(this)),gh(this,k,!1)):Ymm(this)}}unload(){gh(this,null);this.V&&(this.V.abort(),this.V=null);super.unload()}n$(k,F){return qY(this)?k==="loadCustomEndscreenRenderer"?(k=KJ(F,"new"),gh(this,k),!0):null:null}getOptions(){return qY(this)?["loadCustomEndscreenRenderer"]:[]}jd(){if(this.endscreen&&this.endscreen.elements){var k=this.player.getVideoContentRect();if(k&&k.width!==0&&k.height!==0){var F=this.player.getPlayerSize();
if(F&&F.width!==0&&F.height!==0){var a=k.width/k.height;var V=0;var M=-1;for(var C=0;C<vgm.length;C++){var X=Math.abs(F.width-vgm[C]);if(M===-1||V>=X)M=C,V=X}V=cBL[M];this.O&&g.t4(this.O.element,"outline-width",Math.max(F.width,F.height)+"px");for(F=0;F<this.endscreen.elements.length;++F){C=this.endscreen.elements[F].id;M=this.K[C];X=this.C[C];if(!M||!X)continue;const y=X.width*a/X.aspectRatio;var U=Math.round(X.width*k.width);C=Math.round(y*k.height);const n=k.left+Math.round(X.left*k.width),u=k.top+
Math.round(X.top*k.height);g.ws(M.element,U,C);g.N$(M.element,n,u);g.zX(M.element,pYZ);U>256||C>256?g.Dz(M.element,"ytp-ce-large-round"):U>96||C>96?g.Dz(M.element,"ytp-ce-medium-round"):g.Dz(M.element,"ytp-ce-small-round");g.zX(M.element,t2X);U=X.left+X.width/2;X=X.top+y/2;g.Dz(M.element,U<=.5&&X<=.5?"ytp-ce-top-left-quad":U>.5&&X<=.5?"ytp-ce-top-right-quad":U<=.5&&X>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.zX(M.element,cBL);g.Dz(M.element,V);(M=g.wS(document,"div","ytp-ce-expanding-overlay-body",
M.element)[0])&&g.t4(M,"height",`${C}px`)}}}}}onCueRangeEnter(k){if(this.endscreen)if(k.getId()==="ytp-ce-in-endscreen")eN(this,this.endscreen.impressionUrls),(k=g.g4())&&this.endscreen.visualElement&&g.Ds(k,this.endscreen.visualElement),this.D&&(g.Dz(this.D,"ytp-ce-element-show"),this.D.removeAttribute("aria-hidden"),this.player.tO()?g.Dz(this.D,"ytp-ce-hide-button-lower"):g.fa(this.D,"ytp-ce-hide-button-lower"));else{k=k.getId().substring(15);var F=this.K[k],a=this.C[k];g.Dz(F.element,"ytp-ce-element-show");
F.element.removeAttribute("aria-hidden");F=this.player.getRootNode();g.Dz(F,"ytp-ce-shown");eN(this,a.impressionUrls);(F=g.g4())&&g.Ds(F,a.visualElement);this.player.S().W&&g.zD(this.player,"endscreenelementshown",k)}}onCueRangeExit(k){if(k.getId()==="ytp-ce-in-endscreen")this.D&&(g.fa(this.D,"ytp-ce-element-show"),this.D.setAttribute("aria-hidden","true"));else{k=k.getId().substring(15);var F=this.K[k];g.fa(F.element,"ytp-ce-element-show");F.element.setAttribute("aria-hidden","true");F=this.player.getRootNode();
g.fa(F,"ytp-ce-shown");this.player.S().W&&g.zD(this.player,"endscreenelementhidden",k)}}j(k){k.target===window&&(new g.La(()=>{for(const F of Object.values(this.K))g.zX(F.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()}Sd(k){for(const F of Object.values(this.K))k?F.element.setAttribute("hidden",""):F.element.removeAttribute("hidden")}N9(k){this.D&&this.player.getRootNode().removeChild(this.D);
k&&(g.Dz(k,"ytp-ce-hide-button-container"),this.D=k,g.Ii(this.player,this.D,4))}},vgm=[346,426,470,506,570,640,853,1280,1920],cBL="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),t2X=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],pYZ=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var LQB=class{constructor(k,F,a,V){this.value=k;this.target=F;this.showLinkIcon=a;this.K=V}D(){return this.value?this.value:null}},tIz={tZ:"current",lY:"new"};var WQC=class{constructor(k,F,a){this.type=k;this.trigger=F;this.url=a}},Rzm={CLOSE:"close",Qt:"openUrl",SUBSCRIBE:"subscribe"},jmX={Pe:"click",CLOSE:"close",QP:"hidden",a3O:"rollOut",uFw:"rollOver",M4N:"shown"};var SHL=class{constructor(k,F,a,V,M){this.id=k;this.type=F;this.style=a;this.data=M;this.action=V||[]}Rx(){const k=EBm(this,F=>F.type==="openUrl"&&F.url!=null);
return k?k.url:null}},mKz={Ta:"anchored",kR:"branding",CHANNEL:"channel",Be:"cta",kC:"highlightText",UT:"label",PLAYLIST:"playlist",POPUP:"popup",nwU:"speech",SUBSCRIBE:"subscribe",Kx4:"title",VIDEO:"video",Rwl:"website"},ImL={kR:"branding",oN:"card",g3:"drawer",xC:"highlight",sT:"marker",W4:"promotion",TEXT:"text",osl:"widget"};var RbR=[".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}"],
jpS=[".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}"];var W0C=class{constructor(k,F){this.context=k;this.D=F}};var PfB=class{constructor(k,F){this.merchant=k;this.price=F}};var $KB=class extends g.GB{constructor(k,F){super();this.element=k;this.context=F;this.vA=!1;this.PA=new Map;this.L6=new Map;this.context.J.addEventListener(g.oO("annotations_module"),a=>{(a=this.PA.get(a))&&a.apply(this)});
this.context.J.addEventListener(g.nX("annotations_module"),a=>{(a=this.L6.get(a))&&a.apply(this)})}addCueRange(k,F,a,V,M){k=new g.rZ(k,F,{id:a,
namespace:"annotations_module"});V&&this.PA.set(k,V);M&&this.L6.set(k,M);this.context.J.KL([k],1)}D3(){this.context.K.subscribe("resize",this.QX,this)}Zl(){return this.element}Ml(k,F,a,V,M,C){if(this.vA)return!1;C&&(C.stopPropagation(),C.preventDefault());this.navigate(k,a,V,M);return!1}show(){}hide(){}destroy(){g.TJ(this.Zl())}QX(){}navigate(k,F,a,V){const M=k.D();if(M){var C=izQ(M,k.target),X=()=>{k.K&&this.context.J.pauseVideo();const U=this.context.videoData.Ix||!1,y=g.yW(M||"");U&&y&&(y.v||y.list)?
this.context.J.eq(y.v,F,y.list,!1):g.iJ(M||"",C==="current"?"_top":void 0,F)};
C==="new"&&(X(),X=null);Wm(this.context.logger,a,X,V);DL8(M)||(a=g.g4(),V=F.itct,a&&V&&g.zg(a,g.nl(V)))}}p6(){this.PA.clear();this.L6.clear();super.p6()}createElement(k){k=new g.G(k);g.Q(this,k);return k.element}};var OA7=class extends $KB{constructor(k,F,a){super(F,a);this.J=k;this.eventId=null;this.E3=this.a5=this.iI=this.O=this.isInitialized=!1;this.cards=[];this.yX=this.Z=this.Jl=this.C=this.TL=this.D=null;this.I5=[];this.j=this.W=this.LL=this.cA=null;this.T=0;this.VX=new g.La(()=>{},a.B.GV?4E3:3E3);
g.Q(this,this.VX);this.Yw=new g.La(()=>{});
g.Q(this,this.Yw);this.OO=new W0C(a,(V,M,C,X,U,y)=>{Ag(this,V,M,C,X,U,y)});
this.X=new g.G({U:"div",G:"iv-drawer",L:{id:"iv-drawer"},Y:[{U:"div",G:"iv-drawer-header",L:{"aria-role":"heading"},Y:[{U:"span",G:"iv-drawer-header-text"},{U:"button",mN:["iv-drawer-close-button","ytp-button"],L:{"aria-label":"Hide cards",tabindex:"0"}}]},{U:"div",G:"iv-drawer-content"}]});g.Q(this,this.X);this.V=this.X.element;this.n6=new g.rz(this.X,330);g.Q(this,this.n6);this.Dl=g.ki("iv-drawer-header-text",this.V);this.K=g.ki("iv-drawer-content",this.V);this.addCueRange(0,a.videoData.lengthSeconds*
1E3,"",()=>{this.iI&&lD(this,"YOUTUBE_DRAWER_AUTO_OPEN")},()=>{(this.iI=this.O)&&cm(this)});
this.uw=new g.Ms(this);g.Q(this,this.uw);this.J.addEventListener("videodatachange",this.IZ.bind(this))}IZ(){this.j&&vm(this,this.j)}isAvailable(){var k;if(k=!!this.cards.length)(k=this.J.getRootNode())?(k=g.kd(k),k=173<k.width&&173<k.height):k=!1;return k}QX(){const k=this.isAvailable();g.Fg(this.Zl(),k);g.B(this.context.J.getRootNode(),g.zv.IV_DRAWER_ENABLED,k);Vn(this.J)}destroy(){this.J.wM(!1);try{this.J.getRootNode().removeChild(this.V)}catch(k){}g.b0(this.I5);this.uw.K();this.TL&&this.TL.dispose();
this.C&&this.C.dispose();super.destroy()}X5(){this.context.D.listen(g.ki("iv-drawer-close-button",this.V),"click",this.dB,this);this.context.D.listen(this.K,"touchend",()=>{this.VX.start()});
this.context.D.listen(this.K,"scroll",this.Mw,this);this.context.K.subscribe("onHideControls",()=>{this.a5=!0});
this.context.K.subscribe("onShowControls",()=>{this.a5=!1});
this.context.K.subscribe("onVideoAreaChange",()=>{this.a5=g.Np(this.J.getRootNode(),"ytp-autohide")});
this.I5.push(g.G0("iv-button-shown",this.nT,this));this.I5.push(g.G0("iv-button-hidden",this.Ra,this));wZm(this)}findLastIndex(k){if(this.cards.length===0)return 0;const F=g.XX(this.cards,a=>k.wD.startMs>a.wD.startMs||k.wD.startMs===a.wD.startMs&&k.wD.timestamp>=a.wD.timestamp?!0:!1);
return F===-1?0:F+1}dB(){if(this.O){Wm(this.context.logger,LJ(this).hO.close);var k=g.g4();k&&this.W&&g.zg(k,this.W);cm(this)}}Mw(){g.B(this.V,"iv-drawer-scrolled",this.K.scrollTop>0)}nT(){const k=g.g4();var F=LJ(this);F=F?F.LL:this.LL;k&&F&&g.is(k,[F])}Ra(){const k=g.g4();var F=LJ(this);F=F?F.LL:this.LL;k&&F&&g.fl(k,[F])}uI(){const k=LJ(this);Wm(this.context.logger,k.hO.Zk);const F=g.g4();if(F&&k)if(this.J.A("web_infocards_teaser_show_logging_fix")){const a=[];k.fR&&a.push(k.fR);k.LL&&a.push(k.LL);
a.length>0&&g.is(F,a)}else g.is(F,[k.fR,k.LL])}Eu(){const k=g.g4(),F=LJ(this);k&&F&&g.fl(k,[F.fR])}gB(k){const F=LJ(this),a=g.g4();this.D?k?(k=this.context.logger,Wm(k,F.hO.bZ),k.J.sendVideoStatsEngageEvent(4,void 0),a&&F.fR&&g.zg(a,F.fR)):(k=this.context.logger,Wm(k,F.hO.bZ),k.J.sendVideoStatsEngageEvent(4,void 0),a&&F.LL&&g.zg(a,F.LL)):(k=this.context.logger,Wm(k,F.hO.bZ),k.J.sendVideoStatsEngageEvent(4,void 0),a&&this.LL&&g.zg(a,this.LL))}};var Eg8=class extends $KB{constructor(k,F,a){super(k,F);this.annotation=a;this.isActive=!1}D3(){super.D3();XYX(this)}show(){super.show();const k=g.g4();var F=this.annotation.data;k&&F&&(F=F.session_data)&&g.is(k,[g.nl(F.itct)])}hide(){super.hide();const k=g.g4();var F=this.annotation.data;k&&F&&(F=F.session_data)&&g.fl(k,[g.nl(F.itct)])}};var ZAX=class extends Eg8{constructor(k,F,a){super(k,F,a);this.D=null;this.O=!1;this.K=null}show(){if(!this.isActive){super.show();if(!this.O){g.Dz(this.Zl(),"iv-branding");const k=this.annotation.data;this.D=this.createElement({U:"img",mN:["branding-img","iv-click-target"],L:{"aria-label":"Channel watermark",src:k.image_url,width:k.image_width,height:k.image_height}});g.Fg(this.D,!1);const F=this.createElement({U:"button",mN:["branding-img-container","ytp-button"]});F.appendChild(this.D);this.Zl().appendChild(F);
const a=this.annotation.Rx();a&&Ag(this,F,a,this.annotation.id,k.session_data);this.O=!0}g.Fg(this.Zl(),!0);this.isActive=!0;if(this.D){try{UKR(this,this.D)}catch{}g.Dz(this.context.J.getRootNode(),"ytp-branding-shown");this.context.J.getRootNode().style.setProperty("--branding-image-width",`${this.D.getAttribute("width")}px`)}}}hide(){this.isActive&&(super.hide(),g.Fg(this.Zl(),!1),this.isActive=!1,g.fa(this.context.J.getRootNode(),"ytp-branding-shown"))}destroy(){this.K&&(this.K.dispose(),this.K=
null);g.fa(this.context.J.getRootNode(),"ytp-branding-shown");super.destroy()}};var Boz=class{constructor(k,F,a,V,M,C,X){this.D=k;this.O=F;this.B=a;this.videoData=V;this.logger=M;this.J=C;this.K=X}};var ebk=class extends Eg8{constructor(k,F,a){super(k,F,a);this.W=this.isCollapsed=this.X=!1;this.C=5E3;this.K=this.O=this.D=this.V=null;this.T=this.createElement({U:"div",mN:["iv-promo-contents"]});this.Z=new g.La(()=>{this.D.setAttribute("aria-hidden","true");g.Fg(this.O,!1);g.Fg(this.K,!0)},700,this);
g.Q(this,this.Z)}show(){this.isActive||(super.show(),this.X||(ngX(this),this.X=!0),g.Fg(this.Zl(),!0),g.Gn(function(){g.fa(this.Zl(),"iv-promo-inactive")},100,this),this.Zl().removeAttribute("aria-hidden"),this.isActive=!0,jN(this),yB7(this),ogB(this,this.C))}hide(){this.isActive&&(g.Dz(this.Zl(),"iv-promo-inactive"),this.isActive=!1,this.Zl().setAttribute("aria-hidden","true"))}Ml(k,F,a,V,M,C){return this.isCollapsed?!1:super.Ml(k,F,a,V,M,C)}VX(k){this.W=!0;
RP(this,500,k)}OO(){this.W=!1;uvz(this)}I5(k){k.stopPropagation();this.hide()}j(k){k.stopPropagation();jN(this);this.isCollapsed=!0;g.Dz(this.Zl(),"iv-promo-collapsed-no-delay");this.Z.start()}destroy(){this.Z.dispose();super.destroy()}};var Nom=class{constructor(k){this.J=k}};g.dp("annotations_module",class extends g.ZH{constructor(k){super(k);this.I5=this.j=!1;this.loadNumber=0;this.C={};this.logger=new Nom(this.player);this.Z=new g.Ms(this);this.T=this.V=null;this.events=new g.Ms(this);this.TV=this.W=this.D=null;this.D3=[];g.Q(this,this.Z);this.Z.N(this.player,"onVideoAreaChange",()=>{this.publish("onVideoAreaChange")});
this.Z.N(this.player,"onHideControls",()=>{this.publish("onHideControls")});
this.Z.N(this.player,"onShowControls",()=>{this.publish("onShowControls")});
this.Z.N(this.player,"resize",a=>{this.publish("resize",a)});
this.Z.N(this.player,"presentingplayerstatechange",a=>{this.publish("presentingplayerstatechange",a)});
this.subscribe("presentingplayerstatechange",this.VX,this);this.subscribe("resize",this.X,this);this.player.S().cA.subscribe("vast_info_card_add",this.OO,this);g.Q(this,this.events);this.QX=this.createElement({U:"div",G:"video-custom-annotations"});this.K=new g.G({U:"div",mN:["ytp-player-content","ytp-iv-player-content"]});g.Q(this,this.K);g.Ii(this.player,this.K.element,4);this.K.hide();this.O=new g.G({U:"div",mN:["ytp-iv-video-content"]});g.Q(this,this.O);k=this.createElement({U:"div",G:"video-annotations"});
k.appendChild(this.QX);this.O.element.appendChild(k);this.iR()?this.load():this.player.A("web_fix_annotations")&&(this.V=()=>{this.loaded||this.wU()||!this.iR()||(qHC(this),this.load())},this.player.addEventListener("videodatachange",this.V));
const F=this.createElement({U:"style"});(g.GI("HEAD")[0]||document.body).appendChild(F);this.addOnDisposeCallback(()=>{g.TJ(F)});
if(k=F.sheet){for(const a of RbR)k.insertRule(a,0);for(const a of jpS)k.insertRule(a,0)}}n$(k,F){if(!K0k(this.player.S().playerStyle))return null;switch(k){case "loadCustomAnnotationsXml":return(k=g.MP(F))&&Ei(this,k),!0;case "removeCustomAnnotationById":return F&&this.D&&(Yq(this.D,F),Vn(this.player)),!0}return null}getOptions(){return K0k(this.player.S().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]}iR(){const k=this.player.getVideoData(),F=k.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer;
return k.Ix||this.player.isMutedByEmbedsMutedAutoplay()?!1:this.player.A("web_fix_annotations")?HAz(this)?F?.isWatermarkEnforced===!0?!0:F?.isAnnotationsEnabled??!1:!1:HAz(this)}X(){if(this.O){var k=this.player.j4().getVideoContentRect(!0);g.ws(this.O.element,k.width,k.height);g.N$(this.O.element,k.left,k.top)}if(this.D){var F=this.player.Dy();k=this.D;F=F.width;g.B(k.V,"iv-drawer-small",F<=426);g.B(k.V,"iv-drawer-big",F>=1280)}}VX(k){JBz(this,k.state);k.state.D(2)&&(this.tO()&&this.Sw()&&this.player.getPresentingPlayerType()!==
2&&this.CH(!1),this.wM(!1))}load(){super.load();JBz(this,this.player.getPlayerStateObject());this.loadNumber++;const k=this.player.getVideoData();xKC(this,k);g.Ii(this.player,this.O.element,4);this.X();var F=g.t0(k);const a=k.KJ();if(this.player.A("web_fix_annotations")){if(F&&(F.featuredChannel&&lmI(this,F.featuredChannel,F.annotationId||"branding",k.videoId||null,k.eventId||null),F=this.player.getVideoData().getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer,F?.isWatermarkEnforced&&!F?.isAnnotationsEnabled))return;
a&&NY(this,a)}else a&&NY(this,a),F&&F.featuredChannel&&lmI(this,F.featuredChannel,F.annotationId||"branding",k.videoId||null,k.eventId||null);this.TV=g.ki("ytp-cards-button",this.player.getRootNode());k.Fm()&&hb7(this,k)}onVideoDataChange(){}unload(){this.player.Cv("annotations_module");for(const k of Object.keys(this.C))this.C[k].destroy();this.W=null;this.D&&(this.D.destroy(),this.D=null,Vn(this.player));this.j=!1;this.T&&(this.T.abort(),this.T=null);this.I5=!1;this.C={};this.K.hide();super.unload();
this.O.detach();qHC(this)}OO(k){k===this.player.getVideoData().videoId&&(this.loaded?YHL(this):this.load())}tO(){return this.D?.isAvailable()||this.I5}Sw(){return!!this.D&&this.D.O}CH(k,F=!1,a){this.tO();this.D&&(k?a?lD(this.D,a,F):lD(this.D,"YOUTUBE_DRAWER_AUTO_OPEN",F):cm(this.D))}wM(k,F){this.player.publish(k?"cardsteasershow":"cardsteaserhide",F)}p6(){this.player.S().cA.unsubscribe("vast_info_card_add",this.OO,this);g.fa(this.player.getRootNode(),g.zv.IV_DRAWER_OPEN);var k=this.D3,F=g.xH;for(let a=
0,V=k.length;a<V;a++)F.HQ(k[a]);this.D3.length=0;super.p6()}createElement(k){k=new g.G(k);g.Q(this,k);return k.element}});g.dp("creatorendscreen",L0S);})(_yt_player);
